image: Ubuntu1804 # образ для сборки

stack: node 12 # окружение

branches:
  only:
    - main # ветка git

cache: node_modules # кеширование

install:
  install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off # отключаем встроенную в appveyor систему сборки

test_script:
  - npm run lint && npm test # скрипт тестирования